### ISSUE TITLE
AUR Submission Permission

### ISSUE THREAD

**Issue by SethBarberee** [worron/cavalcade#1]
Hi,
This software that you made is amazing! I would like to know if I could submit a PKGBUILD for your program to the AUR for you with your permission. I believe other people would love to use this program too.

**Comment by worron** [comment]
Yes, of course I'll be happy if you make PKGBUILD. I'm doing this for fun and gaining some python experience, so it may have a lack proper distribution. If you will succeed, please remember me to update readme, o just make pull request with fixes.

Devel branch is more featured and stable enough now. I'm planning add some minor changes in future but not right now.

**Comment by SethBarberee** [comment]
Just fixed this up.

PKGBUILD
```
# Maintainer: Seth Barberee <seth.barberee@gmail.com>
pkgname=cavalcade-git
pkgver=20170603
pkgrel=1
pkgdesc="Python GUI wrapper for CAVA utility"
arch=('any')
url="https://github.com/worron/cavalcade"
license=('GPL')
depends=('python-pillow' 'python-cairo' 'cairo' 'cava' 'gtk3' 'python3' 'gst-plu
gins-good')
optdepends=('gstreamer: local audio player functionality')
makedepends=('git')
provides=("cavalcade-git")
source=('cavalcade::git+https://github.com/worron/cavalcade.git#branch=devel')
md5sums=('SKIP')

pkgver(){
    date +%Y%m%d
}
package() {
    cd "$srcdir/cavalcade"
    python3 setup.py install --root="$pkgdir/" --prefix=/usr --optimize=1 --record log.txt
}

```

**Comment by worron** [comment]
Seems like this issue solved. Thanks volunteers for maintaining it.
