### ISSUE TITLE
Question about the exact license

### ISSUE THREAD

**Issue by tocic** [worron/cavalcade#10]
Arch Linux is currently undergoing a transition to SPDX style identifiers, so I'm interested in specifying the exact license version for [this package](https://aur.archlinux.org/packages/cavalcade-git). Does the "GPL" string [here](https://github.com/worron/cavalcade/blob/411591344514983504df0d6d05eaedc4e4cd2749/setup.py#L19) means `GPL-1.0`, `GPL-1.0+`, or something different? You can see the full list [here](https://spdx.org/licenses/).

**Comment by worron** [comment]
Thank you for addressing it, hope it's ok now.
