### ISSUE TITLE
ImportError: No module named 'PIL'

### ISSUE THREAD

**Issue by interact82** [worron/cavalcade#2]
Вот пытаюсь установить cavalcade и вот что из этого вышло:

> sudo python3 setup.py install --record files.txt
> /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'LICENSE'
>   warnings.warn(msg)
> /usr/lib/python3/dist-packages/setuptools/dist.py:342: UserWarning: The version specified ('0.9.dev5-g073b631') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
>   "details." % self.metadata.version
> running install
> running bdist_egg
> running egg_info
> writing cavalcade.egg-info/PKG-INFO
> writing dependency_links to cavalcade.egg-info/dependency_links.txt
> writing requirements to cavalcade.egg-info/requires.txt
> writing entry points to cavalcade.egg-info/entry_points.txt
> writing top-level names to cavalcade.egg-info/top_level.txt
> package init file 'cavalcade/gui/__init__.py' not found (or not a regular file)
> package init file 'cavalcade/data/__init__.py' not found (or not a regular file)
> reading manifest file 'cavalcade.egg-info/SOURCES.txt'
> writing manifest file 'cavalcade.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/common.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/pixbuf.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/playerpage.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/run.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/player.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/mainapp.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/__init__.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/canvas.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/autocolor.py -> build/bdist.linux-x86_64/egg/cavalcade
> creating build/bdist.linux-x86_64/egg/cavalcade/data
> copying build/lib/cavalcade/data/cava.ini -> build/bdist.linux-x86_64/egg/cavalcade/data
> copying build/lib/cavalcade/data/main.ini -> build/bdist.linux-x86_64/egg/cavalcade/data
> copying build/lib/cavalcade/data/DefaultWallpaper.svg -> build/bdist.linux-x86_64/egg/cavalcade/data
> copying build/lib/cavalcade/visualpage.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/settings.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/version.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/drawing.py -> build/bdist.linux-x86_64/egg/cavalcade
> creating build/bdist.linux-x86_64/egg/cavalcade/gui
> copying build/lib/cavalcade/gui/settings.ui -> build/bdist.linux-x86_64/egg/cavalcade/gui
> copying build/lib/cavalcade/gui/winstate.ui -> build/bdist.linux-x86_64/egg/cavalcade/gui
> copying build/lib/cavalcade/gui/appmenu.ui -> build/bdist.linux-x86_64/egg/cavalcade/gui
> copying build/lib/cavalcade/gui/playerpage.glade -> build/bdist.linux-x86_64/egg/cavalcade/gui
> copying build/lib/cavalcade/gui/visualpage.glade -> build/bdist.linux-x86_64/egg/cavalcade/gui
> copying build/lib/cavalcade/gui/colors.glade -> build/bdist.linux-x86_64/egg/cavalcade/gui
> copying build/lib/cavalcade/gui/cavapage.glade -> build/bdist.linux-x86_64/egg/cavalcade/gui
> copying build/lib/cavalcade/colordata.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/config.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/cavapage.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/logger.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/cava.py -> build/bdist.linux-x86_64/egg/cavalcade
> copying build/lib/cavalcade/adata.py -> build/bdist.linux-x86_64/egg/cavalcade
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/common.py to common.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/pixbuf.py to pixbuf.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/playerpage.py to playerpage.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/run.py to run.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/player.py to player.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/mainapp.py to mainapp.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/__init__.py to __init__.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/canvas.py to canvas.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/autocolor.py to autocolor.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/visualpage.py to visualpage.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/settings.py to settings.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/version.py to version.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/drawing.py to drawing.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/colordata.py to colordata.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/config.py to config.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/cavapage.py to cavapage.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/logger.py to logger.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/cava.py to cava.cpython-35.pyc
> byte-compiling build/bdist.linux-x86_64/egg/cavalcade/adata.py to adata.cpython-35.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying cavalcade.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying cavalcade.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying cavalcade.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying cavalcade.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying cavalcade.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying cavalcade.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> zip_safe flag not set; analyzing archive contents...
> cavalcade.__pycache__.config.cpython-35: module references __file__
> cavalcade.__pycache__.run.cpython-35: module references __file__
> cavalcade.__pycache__.common.cpython-35: module references __file__
> cavalcade.__pycache__.version.cpython-35: module references __file__
> creating 'dist/cavalcade-0.9.dev5_g073b631-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing cavalcade-0.9.dev5_g073b631-py3.5.egg
> creating /usr/local/lib/python3.5/dist-packages/cavalcade-0.9.dev5_g073b631-py3.5.egg
> Extracting cavalcade-0.9.dev5_g073b631-py3.5.egg to /usr/local/lib/python3.5/dist-packages
> Adding cavalcade 0.9.dev5-g073b631 to easy-install.pth file
> Installing cavalcade script to /usr/local/bin
> 
> Installed /usr/local/lib/python3.5/dist-packages/cavalcade-0.9.dev5_g073b631-py3.5.egg
> Processing dependencies for cavalcade===0.9.dev5-g073b631
> Searching for setuptools==33.1.1
> Best match: setuptools 33.1.1
> Adding setuptools 33.1.1 to easy-install.pth file
> Installing easy_install script to /usr/local/bin
> 
> Using /usr/lib/python3/dist-packages
> Finished processing dependencies for cavalcade===0.9.dev5-g073b631
> writing list of installed files to 'files.txt'
> 
============================
cavalcade --help                                

> Traceback (most recent call last):
>   File "/usr/local/bin/cavalcade", line 11, in <module>
>     load_entry_point('cavalcade===0.9.dev5-g073b631', 'console_scripts', 'cavalcade')()
>   File "/usr/local/lib/python3.5/dist-packages/cavalcade-0.9.dev5_g073b631-py3.5.egg/cavalcade/run.py", line 32, in run
>     from cavalcade.mainapp import MainApp
>   File "/usr/local/lib/python3.5/dist-packages/cavalcade-0.9.dev5_g073b631-py3.5.egg/cavalcade/mainapp.py", line 10, in <module>
>     from cavalcade.autocolor import AutoColor
>   File "/usr/local/lib/python3.5/dist-packages/cavalcade-0.9.dev5_g073b631-py3.5.egg/cavalcade/autocolor.py", line 9, in <module>
>     from PIL import Image
> ImportError: No module named 'PIL'

**Comment by worron** [comment]
Для полноценной работы приложению нужен модуль `pillow` третьего питона. Я пытался сделать его опциональным, но похоже накосячил, посмотрю на выходных. Если не напрягает, можно просто доустановить pillow в систему, вероятно это решит проблему.

**Comment by worron** [comment]
Посмотрел, действительно мой косяк, долно быть исправлено теперь.

**Comment by interact82** [comment]
Запускается, появляется окно cavalcade можно открыть настройки, но вот фай не воспроизводится. Подскажи в какую сторону копать. 

>  cavalcade --play Alan.mp3
> ERROR: 2018-03-10 17:25:49,254 player.py:_on_message():L121 Playback error gst-resource-error-quark: Ресурс не найден. (3)
> gstfilesrc.c(535): gst_file_src_start (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin1/GstFileSrc:source:
> No such file "/Alan.mp3"

**Comment by worron** [comment]
Нужен полный путь к файлу вроде `/home/user/Music/Alan.mp3`.

**Comment by interact82** [comment]
Спасибо всё работает!!! И за Awesome WM config
