### ISSUE TITLE
Support for more than 64 bars

### ISSUE THREAD

**Issue by Thesola10** [worron/cavalcade#3]
When manually modifying `cava.conf` I noticed that the program starts to see a jitter/desync whenever the number of bars was pushed above 64. Since I am using the program as a background thing and I want 80 bars that is problematic. The bars do get narrower as desired, so I don't think it's an auto-detect issue.

Is there a reason why this problem exists, and a chance it could be fixed? I feel like it is known since the GUI configurator does not let the number of bars above 64.

**Comment by worron** [comment]
Old bug which I try to avoid setting 64 bar limit.

I didn't investigate this problem properly, but seems default cava settings `bar_width=2`, `bar_spacing=1` somehow affect max bars number (actually its shouldn't) limiting it to 200/(2+1) . Setting summary bar and space width to  1 should do the trick.

You can test added fix (config update needed) and report if it works.

**Comment by Thesola10** [comment]
Setting `bar_width=1` and `bar_spacing=1` allowed me to set 80 bars, I think this should be the config default. Also maybe bug the cava project upstream?

**Comment by worron** [comment]
>Also maybe bug the cava project upstream?

It's quite possible.

Anyway, config fix added and full bars number should work now. Thanks for report and testing.
