### ISSUE TITLE
Question about release tags bumping

### ISSUE THREAD

**Issue by tocic** [worron/cavalcade#5]
Hello, I'm the maintainer of [cavalcade in AUR](https://aur.archlinux.org/packages/cavalcade). Thanks for developing this utility.
Do you plan to update [release tags](https://github.com/worron/cavalcade/tags) in the future? Or do you prefer packagers to build from the `devel`'s top commit?

**Comment by worron** [comment]
No future updates planned, just using devel branch will be better I think.

And thank you for maintaining AUR package, very appreciated.
