### ISSUE TITLE
hide cursor in fullscreen mode?

### ISSUE THREAD

**Issue by min-xu-ai** [worron/cavalcade#7]
Thanks for this great app! I love it.

In fullscreen mode (with gnome), the cursor is showing. Is there a way to hide it when it is not moving?

Thanks in advance!

**Comment by worron** [comment]
Quite reasonable idea, so I added cursor auto hide feature to app. Try to update app from `devel` branch and update your config (`~/.config/cavalcade/main.ini`) with [new option](https://github.com/worron/cavalcade/commit/5a41710263d4442822c29b8ac5d5955e5bf23f81#diff-f271e39bab5811e228ccbef6bd8b2188b66916513f7d70942dbf885472a856f5). This `cursor_hide_timeout` opton allows configurate auto hide timeout in seconds.

**Comment by min-xu-ai** [comment]
Just tried it. Works great!

I don't see a config in the UI for change this config value though. Does it mean user have to edit the ini file?

**Comment by worron** [comment]
>Does it mean user have to edit the ini file?

Exactly, for now at least.

There are few "low level" settings in this app which available by config file only. It does not feels worth it making gui for things which will be configured once at best. Right now have no decision about gui for  `cursor_hide_timeout` option, may be will reconsider this later.

**Comment by min-xu-ai** [comment]
Sounds good 👌

**Comment by min-xu-ai** [comment]
Sounds good 👌
