### ISSUE TITLE
Building issues with newer python and setuptools

### ISSUE THREAD

**Issue by tocic** [worron/cavalcade#9]
I'm facing the following issues when trying to install the app with `Python 3.11.3` and `python-setuptools 67.7.0`:

1. The error

```
  File "/usr/lib/python3.11/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.8-makepkg-g5a41710'
```

and the warning

```
/usr/lib/python3.11/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: '0.8-makepkg-g5a41710'.
!!

        ********************************************************************************
        Version '0.8-makepkg-g5a41710' is not valid according to PEP 440.

        Please make sure to specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.

        By 2023-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
```

There was only the warning until the recent versions, but now the above error blocks the build. See https://github.com/pypa/setuptools/issues/3772.

The reason is that `makepkg` (a tool used for creating packages in Arch) [creates a temporary branch called "makepkg"](https://gitlab.archlinux.org/pacman/pacman/-/blob/262aa6c24ee85f96882c3726cc58e2da31e41bfe/scripts/libmakepkg/source/git.sh.in#L128) when building a package from VCS sources (for build isolation). Then your script decides we're not on `devel`:

https://github.com/worron/cavalcade/blob/5a41710263d4442822c29b8ac5d5955e5bf23f81/cavalcade/version.py#L22-L28

and the version becomes `0.8-makepkg-g5a41710`. What do you think about deleting this last if branch and always suffixing the version with `dev` to make it compliant with [PEP 440](https://peps.python.org/pep-0440/#developmental-releases)?

2. The warning

```
/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
```

This is not critical now, but may also break the builds in the future. Consider switching to [PEP 517](https://peps.python.org/pep-0517) if you have time.

**Comment by tocic** [comment]
Here is [the temporary patch](https://aur.archlinux.org/cgit/aur.git/commit/?h=cavalcade-git&id=132f68ce8a8d5bd07e60355541e67baa3f2a1c6f) that fixed the build for me:

```diff
elif branch == _DEVELOPMENT_BRANCH:
    version = "%.1f.dev%s-%s" % (float(v) + 0.1, n, commit)
else:
-   version = "%s-%s-%s" % (v, branch, commit)
+   version = "%s.dev%s+%s" % (v, n, commit)
```

The application works now, but I also had to change the `image.default` path in `~/.config/cavalcade/main.ini` to `/usr/lib/python3.11/site-packages/cavalcade/data/DefaultWallpaper.svg`.

**Comment by worron** [comment]
Thank you for providing all the details. I totally agree about your approach to version format, corresponding fixes were added.

About the second problem, I'll try to look into it at an early date.

**Comment by tocic** [comment]
Thank you for the quick resolution! Can confirm that the problem is fixed now.
